spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pw44s
    username: postgres
    password: ids0207
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8081
  servlet:
    context-path: /api