  spring:
    application:
      name: programacao-web
    datasource:
      generate-unique-name: false
  server:
    port: 8081
    servlet:
      context-path: /api
  h2:
    console:
      enabled: true
      path: /h2-console